test_task:
  only_if: $CIRRUS_TAG == ''
  container:
    matrix:
      image: fedora:28
      image: fedora:29
      image: fedora:30
  install_script:
    - dnf --assumeyes install python3-{createrepo_c,libselinux}
    - pip3 install --editable .[tests]
  test_script: pytest
