test_task:
  container:
    matrix:
      image: python:3.6
      image: python:3.7
  pip_cache:
    folder: ~/.cache/pip
    fingerprint_script: pip freeze
  install_script:
    - apt update
    - apt --assume-yes install cmake gcc libbz2-dev libcurl4-openssl-dev libexpat1-dev libglib2.0-dev liblzma-dev libmagic-dev librpm-dev libsqlite3-dev libssl-dev libxml2-dev zlib1g-dev
    - pip install .[tests]
  test_script: pytest
