test_task:
  only_if: $CIRRUS_TAG == ''
  container:
    matrix:
      image: fedora:33
      image: fedora:34
  install_script:
    - dnf --assumeyes install python3-{createrepo_c,libselinux,pip}
    - pip3 install --editable .[tests]
  test_script: pytest
